---
- name: Get switch config
  hosts: ios_devices
  gather_facts: no

  vars:
    test: abc

  tasks:
    - name: Get Switch config
      ios_facts:
      gather_subset:
        - config
