---
- name: Get switch config
  hosts: d1

  vars:
    ntp_servers:
      - 1.1.1.1
      - 2.2.2.2

  tasks:
    - name: Configure NTP
      ios_config:
        lines: "{{ lookup('template', 'ntp-config.j2') }}"
